package com.testgithub.common

enum class MyError {
    SIGN_OUT_ERROR,
    ADD_REPOSITORY_TO_FAVORITE_ERROR,
    LOAD_REPOSITORIES_ERROR,
    LOAD_FAVORITE_REPOSITORIES_ERROR,
    DELETE_FAVORITE_REPOSITORY_ERROR
}